### ISSUE TITLE
Possibility to merge / exchange features

### ISSUE THREAD

**Issue by naugtur** [nodejs/create-node-meeting-artifacts#1]
https://github.com/naugtur/wg-meeting-cli is my tool for meeting setup automation.

No integration with google services there, but got the scaffolding for an ok user experience in terminal done.

I'll look into yours and come back here with ideas on what we could do.

**Comment by mhdawson** [comment]
Sounds good.  I don't have any doc yet so if you have questions just let me know.

Currently it is hard coded for 'TSC' but that will be easy to change and is the next thing on my list.

**Comment by cPhost** [comment]
@mhdawson any way i can help with this repo.

**Comment by mhdawson** [comment]
@cPhost there are a couple of issues which were my next TODO's if you want to work on one of those it would be great.

**Comment by mhdawson** [comment]
There have been no comments in over 7 years, closing.
