### ISSUE TITLE
website redesign zoom link

### ISSUE THREAD

**Issue by benhalverson** [nodejs/create-node-meeting-artifacts#116]
@joesepi @mhdawson 
The website zoom link displays an error. Can a new one be provided?

![image](https://user-images.githubusercontent.com/7907232/189503237-fc49289e-78e3-4b29-b454-556a50fe0c78.png)

**Comment by mhdawson** [comment]
@benhalverson who is going to chair the meetings, they will need zoom access. If they have that they should also be able to create the meeting?
