### ISSUE TITLE
Release WG meeting issues are not being created

### ISSUE THREAD

**Issue by richardlau** [nodejs/create-node-meeting-artifacts#147]
For the last two Release WG meetings (11 Jan 2024 and 14 Dec 2023[1]) the expected issues in https://github.com/nodejs/Release have not been created. It looks like meeting issues are still being created for the other working groups/teams so it would be good to understand/resolve why the process isn't working for the Release WG.

[1] Note https://github.com/nodejs/Release/issues/971 exists but I had to [ask @mhdawson to generate it](https://openjs-foundation.slack.com/archives/C019MGJQ8RH/p1702505253980149).

**Comment by mhdawson** [comment]
@richard, the tool depends on the name in the calendar matching what is in the templates so its worth double checking that. The google APIs also seem a bit "flaky" sometimes in terms of matching.  If you can give me a few days notice in advance of a meeting for a meeting when the issue has not been generated I can see if just running the tooling generates the meeting or not and if not do some debugging.

**Comment by richardlau** [comment]
> @richardlau, the tool depends on the name in the calendar matching what is in the templates so its worth double checking that. The google APIs also seem a bit "flaky" sometimes in terms of matching. If you can give me a few days notice in advance of a meeting for a meeting when the issue has not been generated I can see if just running the tooling generates the meeting or not and if not do some debugging.

@mhdawson FYI the next Release WG meeting is next week, Thursday 8th February 2023. It's probably too early for the issue to normally be generated, but I'll mention it now as you're away next week.

**Comment by mhdawson** [comment]
@richardlau did you check that the templates and entry in the calendar match?

**Comment by richardlau** [comment]
> @richardlau did you check that the templates and entry in the calendar match? Unfortunately for me to easily debug it needs to be between the Monday the issue would be generated and the meeting itself and I will be away before the next one.

AFAICT yes, they match
![image](https://github.com/nodejs/create-node-meeting-artifacts/assets/5445507/86127b18-1dd4-442b-8335-d26ab2e17f27)
https://github.com/nodejs/create-node-meeting-artifacts/blob/a7138ba7e2ce3a03856dbd793b75fdc0696873ba/templates/meeting_base_Release#L1

**Comment by mhdawson** [comment]
All I can think of at this point it some rate limiting by github.  Split up the creation on mondays into two different jobs that run an hour appart to see if that helps.
