### ISSUE TITLE
Create Mentorship meeting automation

### ISSUE THREAD

**Issue by dshaw** [nodejs/create-node-meeting-artifacts#34]
In [Mentorship Program Administrative Tasks #95](https://github.com/nodejs/mentorship/issues/95), I took the action item to setup create-node-meeting-artifacts for [mentorship-agenda](https://github.com/nodejs/mentorship/labels/mentorship-agenda).

**Comment by mhdawson** [comment]
I think this issue is long state closing. Please let me know if that was not the right thing to do.
