### ISSUE TITLE
investigate CodiMD for meeting doc collaboration

### ISSUE THREAD

**Issue by boneskull** [nodejs/create-node-meeting-artifacts#72]
Currently, we use Google Docs for real-time collaboration during meetings (agenda, attendees, minutes, etc.)

This is awkward, because Google Docs does not support Markdown, which we use for these documents.

[CodiMD](https://github.com/hackmdio/codimd) is an open-source project which allows real-time, collaborative editing of Markdown documents.  The [feature list](https://hackmd.io/features) is pretty extensive.

We (me or someone else) should investigate CodiMD and see if it can better serve our purposes.  Essentially, I think the main requirement (besides the whole real-time collaboration thing) is that we are able to automate the creation of the doc (which is one of the purposes of this repo!).  

[hackmd.io](https://hackmd.io) is also an option; this is a paid/free offering running (roughly?) the same codebase.  Maybe easier to think of HackMD as a "public instance" of CodiMD.  _Anyway_, I couldn't figure out how to actually pay them for anything, or what it costs, but it may be as simple as just asking for a subdomain.

**Comment by boneskull** [comment]
Here are some notes:

1. CodiMD is a Node.js project running Express w/ a custom frontend architecture
1. Assuming the CSP is setup correctly, it appears all it would take to automate the creation of the meeting note would be to `POST` to a URL.  
1. Users can use various SSO providers (including GitHub) to login.
1. If we need to modify the source for whatever reason, let it be known that CodiMD is licensed AGPL

**Comment by mhdawson** [comment]
One suggestion in terms of roll-out.  I'd prefer if this was added as an option that can be enabled in the  `meeting_base` file for each team/group that is using the generator.  For example possibly by adding an option like

```
USE_HACKME=Y
```

**Comment by boneskull** [comment]
> I'd prefer if this was added as an option

Works for me.

I've reached out to the HackMD team and explained our use-case.  They are excited to be able to support us, but automating the document generating via API may need some implementation work on their end.  

(They are also working on a GitHub integration which could enable us (I think) to create a boilerplate meeting doc in a repo, automatically load it into HackMD, then commit the changes back when we are finished. )

What I'd like to do is _manually_ try using HackMD for some meetings; this means copy/paste the Google doc contents into a HackMD document and share the URL.  We can then get people's thoughts on the tool.  If it sounds good, I'll work with the HackMD team to get us set up.

Thanks to @jorydotcom for bringing HackMD to my attention :smile:

**Comment by bnb** [comment]
I would 100% love to use HackMD as an alternative for Google Docs, if this is still a thing. I've had the opportunity to use it in the Electron groups recently and it's such a massive improvement.

**Comment by boneskull** [comment]
Alright, I've had a chance to use HackMD a bit, and I'm quite happy with it.

I don't think @nodejs/tooling will be using Google Docs for minutes going forward.

See a profile I made here: https://hackmd.io/@nodejs-tooling

@mhdawson Practically, how would we set this up so it uses Google Docs for our group?  Obviously there's code involved, but not sure if that will need to be a completely different cron job somewhere...

**Comment by mhdawson** [comment]
You can look at the code here: https://github.com/nodejs/create-node-meeting-artifacts/blob/master/create-node-meeting-artifacts.js.

What you'd need to to is PR code which would create the HackMD document instead of the creating a google doc.  That starts around line 120.  It would need to be an option that could be configured in the meeting_base_tooling file and used to select the new option instead of the current function: https://github.com/nodejs/create-node-meeting-artifacts/blob/master/templates/meeting_base_tooling

**Comment by boneskull** [comment]
Thanks. I’ll work on this.

**Comment by boneskull** [comment]
There was a _very_ recently-released [command-line tool](/hackmdio/codimd-cli) to help assist here.  The [PR referenced above](/hackmdio/codimd-cli/pull/5) is needed, unless I want to hand-roll a REST client.

@mhdawson How do we manage credentials?  hackmd.io (or even a custom instance) will need a user/password in order to import a markdown file, of course.

**Comment by mhdawson** [comment]
@boneskull I've managed those locally so far as I'm running on my own machine. When that moves we'll need to change that. For now if you figure it all out and add support I'd get my own credentials and store them locally to start.

**Comment by mhdawson** [comment]
@boneskull just wondering if this is still something you are planning to move forward.

**Comment by boneskull** [comment]
nope 😀

**Comment by mhdawson** [comment]
@boneskull thanks, closing
