### ISSUE TITLE
Contributing: How to PR on template-related matters

### ISSUE THREAD

**Issue by SMotaal** [nodejs/create-node-meeting-artifacts#77]
There are a two types of template-related matters:

1. Subtle stylistic/notation things — like [`*Extracted…`](https://github.com/nodejs/create-node-meeting-artifacts/search?q=*Extracted&unscoped_q=*Extracted) being meant as a bullet can sometimes trip the linter to think `*Extracted…accidentally*` in italics.

2. Additional things that can help improve the overall proess — like adding the following to help close the respective PRs and issues more organically:

```md
<!-- 

Once done editing, you can export, clean up markdown and open PR — use this link:

$MINUTES_DOC$/export?format=txt

-->
```

---

**Questions**

1. If someone wanted to make changes, how do they safely make them so that all templates are properly updated and standardized? Please see above link for context.

2. Would those two suggestions be something that folks here want me to do per the answer for question 1? Glad to do it.

Thanks 😄

**Comment by mhdawson** [comment]
To submit updates you would need to create PR's against the templates. Generally we'd want the chair/leader for a particular meeting to agree to the change to the template.  That probably means that a different PR for the templates related to each meeting.

The suggestion using export?format=txt is quite helpful. It will save me having to cut/paste the content and instead use curl to get the contents for the PR instead.  Adding that kind of info int the README.md or templates makes sense to me.

**Comment by SMotaal** [comment]
So if I understand, we do actually need to update the markdown files directly, they are not generated from boilerplate and interpolations.

- [ ] Trial-by-fire it is… Gladly, just as soon as I can allot time to (be in gear to handle it carefully) next week or so.

---

We might want to explore down the road some ideas for regenerating where there clear separation between opt-in boilerplate (and maybe variants) aspects interlaced with custom interpolations, so one PR for opt-in boilerplate would a single place for discussion.

**Comment by mhdawson** [comment]
The issue and the google doc are both automatically generated.  Creating the PR after the meeting is a manual cut/paste from the google doc.

**Comment by mhdawson** [comment]
I'm going to close this as there has been no discussion for a couple of years. Please let me know if you feel that was not the right thing to do and feel free to re-open.
