### ISSUE TITLE
Change default HOST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/create-node-meeting-artifacts#82]
Default host is `Node.js Foundation` which no longer exists. Believe this needs a change in one of the lower level dependencies.

**Comment by richardlau** [comment]
I think it comes from here: https://github.com/nodejs/make-node-meeting/blob/6e0b28c82a8b672274f9b4f548b6bf681e8c1e79/make-node-meeting.sh#L50

**Comment by mhdawson** [comment]
PR https://github.com/nodejs/make-node-meeting/pull/39

**Comment by mhdawson** [comment]
Once approve I can apply test to the environment where the automation runs. Will plan to do so once I'm back from vacation.

**Comment by mhdawson** [comment]
The PR was merged, closing
